# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'nb_gui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1080, 795)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.action_mode = QGroupBox(self.centralwidget)
        self.action_mode.setObjectName(u"action_mode")
        self.action_mode.setGeometry(QRect(10, 10, 251, 61))
        self.action_normal = QRadioButton(self.action_mode)
        self.action_normal.setObjectName(u"action_normal")
        self.action_normal.setGeometry(QRect(10, 20, 81, 31))
        self.action_voice = QRadioButton(self.action_mode)
        self.action_voice.setObjectName(u"action_voice")
        self.action_voice.setGeometry(QRect(90, 20, 61, 31))
        self.action_clingy = QRadioButton(self.action_mode)
        self.action_clingy.setObjectName(u"action_clingy")
        self.action_clingy.setGeometry(QRect(170, 20, 71, 31))
        self.camera_light_mode = QGroupBox(self.centralwidget)
        self.camera_light_mode.setObjectName(u"camera_light_mode")
        self.camera_light_mode.setGeometry(QRect(810, 230, 251, 61))
        self.constant_button = QPushButton(self.camera_light_mode)
        self.constant_button.setObjectName(u"constant_button")
        self.constant_button.setGeometry(QRect(10, 20, 111, 31))
        self.flash_button = QRadioButton(self.camera_light_mode)
        self.flash_button.setObjectName(u"flash_button")
        self.flash_button.setGeometry(QRect(150, 30, 61, 16))
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(270, 10, 531, 401))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.image_label = QLabel(self.horizontalLayoutWidget)
        self.image_label.setObjectName(u"image_label")
        self.image_label.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.image_label)

        self.realtime_plotting = QGroupBox(self.centralwidget)
        self.realtime_plotting.setObjectName(u"realtime_plotting")
        self.realtime_plotting.setGeometry(QRect(9, 419, 591, 271))
        self.plottingGraphicsView = QGraphicsView(self.realtime_plotting)
        self.plottingGraphicsView.setObjectName(u"plottingGraphicsView")
        self.plottingGraphicsView.setGeometry(QRect(15, 21, 561, 241))
        self.moving_speed = QGroupBox(self.centralwidget)
        self.moving_speed.setObjectName(u"moving_speed")
        self.moving_speed.setGeometry(QRect(10, 80, 251, 61))
        self.speed_slider = QSlider(self.moving_speed)
        self.speed_slider.setObjectName(u"speed_slider")
        self.speed_slider.setGeometry(QRect(10, 20, 231, 22))
        self.speed_slider.setOrientation(Qt.Horizontal)
        self.control_panel = QGroupBox(self.centralwidget)
        self.control_panel.setObjectName(u"control_panel")
        self.control_panel.setGeometry(QRect(10, 150, 251, 261))
        self.gridLayoutWidget = QWidget(self.control_panel)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(9, 19, 239, 231))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setVerticalSpacing(11)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.left_button = QPushButton(self.gridLayoutWidget)
        self.left_button.setObjectName(u"left_button")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_button.sizePolicy().hasHeightForWidth())
        self.left_button.setSizePolicy(sizePolicy)
        self.left_button.setMaximumSize(QSize(75, 1677721))

        self.gridLayout.addWidget(self.left_button, 1, 0, 1, 1)

        self.right_button = QPushButton(self.gridLayoutWidget)
        self.right_button.setObjectName(u"right_button")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.right_button.sizePolicy().hasHeightForWidth())
        self.right_button.setSizePolicy(sizePolicy1)

        self.gridLayout.addWidget(self.right_button, 1, 2, 1, 1)

        self.backward_button = QPushButton(self.gridLayoutWidget)
        self.backward_button.setObjectName(u"backward_button")
        sizePolicy1.setHeightForWidth(self.backward_button.sizePolicy().hasHeightForWidth())
        self.backward_button.setSizePolicy(sizePolicy1)

        self.gridLayout.addWidget(self.backward_button, 2, 1, 1, 1)

        self.forward_button = QPushButton(self.gridLayoutWidget)
        self.forward_button.setObjectName(u"forward_button")
        sizePolicy1.setHeightForWidth(self.forward_button.sizePolicy().hasHeightForWidth())
        self.forward_button.setSizePolicy(sizePolicy1)

        self.gridLayout.addWidget(self.forward_button, 0, 1, 1, 1)

        self.stop_button = QPushButton(self.gridLayoutWidget)
        self.stop_button.setObjectName(u"stop_button")
        sizePolicy1.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy1)

        self.gridLayout.addWidget(self.stop_button, 1, 1, 1, 1)

        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 700, 591, 61))
        self.start_button = QPushButton(self.groupBox_5)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(10, 20, 151, 31))
        self.pause_button = QPushButton(self.groupBox_5)
        self.pause_button.setObjectName(u"pause_button")
        self.pause_button.setGeometry(QRect(190, 20, 161, 31))
        self.save_button = QPushButton(self.groupBox_5)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(380, 20, 161, 31))
        self.serial_device = QGroupBox(self.centralwidget)
        self.serial_device.setObjectName(u"serial_device")
        self.serial_device.setGeometry(QRect(610, 420, 451, 61))
        self.detect_button = QPushButton(self.serial_device)
        self.detect_button.setObjectName(u"detect_button")
        self.detect_button.setGeometry(QRect(120, 20, 91, 31))
        self.auto_save_check = QRadioButton(self.serial_device)
        self.auto_save_check.setObjectName(u"auto_save_check")
        self.auto_save_check.setGeometry(QRect(340, 20, 89, 31))
        self.serial_port_combb = QComboBox(self.serial_device)
        self.serial_port_combb.setObjectName(u"serial_port_combb")
        self.serial_port_combb.setGeometry(QRect(10, 20, 91, 31))
        self.connect_button = QPushButton(self.serial_device)
        self.connect_button.setObjectName(u"connect_button")
        self.connect_button.setGeometry(QRect(230, 20, 101, 31))
        self.camera_source_box = QGroupBox(self.centralwidget)
        self.camera_source_box.setObjectName(u"camera_source_box")
        self.camera_source_box.setGeometry(QRect(810, 70, 251, 71))
        self.cam_ip_label = QLabel(self.camera_source_box)
        self.cam_ip_label.setObjectName(u"cam_ip_label")
        self.cam_ip_label.setGeometry(QRect(10, 20, 141, 20))
        self.ip_modify_button = QPushButton(self.camera_source_box)
        self.ip_modify_button.setObjectName(u"ip_modify_button")
        self.ip_modify_button.setGeometry(QRect(184, 20, 61, 31))
        self.car_ip_label = QLabel(self.camera_source_box)
        self.car_ip_label.setObjectName(u"car_ip_label")
        self.car_ip_label.setGeometry(QRect(10, 40, 141, 20))
        self.battery_level_box = QGroupBox(self.centralwidget)
        self.battery_level_box.setObjectName(u"battery_level_box")
        self.battery_level_box.setGeometry(QRect(810, 10, 251, 51))
        self.battery_label = QLabel(self.battery_level_box)
        self.battery_label.setObjectName(u"battery_label")
        self.battery_label.setGeometry(QRect(10, 10, 101, 31))
        self.battery_bar = QProgressBar(self.battery_level_box)
        self.battery_bar.setObjectName(u"battery_bar")
        self.battery_bar.setGeometry(QRect(130, 12, 121, 31))
        self.battery_bar.setValue(24)
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(610, 500, 451, 261))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.angle_pid_box = QGroupBox(self.verticalLayoutWidget)
        self.angle_pid_box.setObjectName(u"angle_pid_box")
        self.angle_p = QLabel(self.angle_pid_box)
        self.angle_p.setObjectName(u"angle_p")
        self.angle_p.setGeometry(QRect(10, 20, 111, 21))
        self.horizontalSlider_2 = QSlider(self.angle_pid_box)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setGeometry(QRect(149, 20, 291, 21))
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)
        self.horizontalSlider_3 = QSlider(self.angle_pid_box)
        self.horizontalSlider_3.setObjectName(u"horizontalSlider_3")
        self.horizontalSlider_3.setGeometry(QRect(150, 60, 291, 21))
        self.horizontalSlider_3.setOrientation(Qt.Horizontal)
        self.horizontalSlider_4 = QSlider(self.angle_pid_box)
        self.horizontalSlider_4.setObjectName(u"horizontalSlider_4")
        self.horizontalSlider_4.setGeometry(QRect(150, 100, 291, 21))
        self.horizontalSlider_4.setOrientation(Qt.Horizontal)
        self.angle_i = QLabel(self.angle_pid_box)
        self.angle_i.setObjectName(u"angle_i")
        self.angle_i.setGeometry(QRect(10, 60, 111, 21))
        self.angle_d = QLabel(self.angle_pid_box)
        self.angle_d.setObjectName(u"angle_d")
        self.angle_d.setGeometry(QRect(10, 100, 111, 21))

        self.verticalLayout.addWidget(self.angle_pid_box)

        self.speed_pid_box = QGroupBox(self.verticalLayoutWidget)
        self.speed_pid_box.setObjectName(u"speed_pid_box")
        self.speed_p = QLabel(self.speed_pid_box)
        self.speed_p.setObjectName(u"speed_p")
        self.speed_p.setGeometry(QRect(10, 20, 111, 21))
        self.horizontalSlider_5 = QSlider(self.speed_pid_box)
        self.horizontalSlider_5.setObjectName(u"horizontalSlider_5")
        self.horizontalSlider_5.setGeometry(QRect(149, 20, 291, 21))
        self.horizontalSlider_5.setOrientation(Qt.Horizontal)
        self.speed_i = QLabel(self.speed_pid_box)
        self.speed_i.setObjectName(u"speed_i")
        self.speed_i.setGeometry(QRect(10, 60, 111, 21))
        self.horizontalSlider_6 = QSlider(self.speed_pid_box)
        self.horizontalSlider_6.setObjectName(u"horizontalSlider_6")
        self.horizontalSlider_6.setGeometry(QRect(150, 60, 291, 21))
        self.horizontalSlider_6.setOrientation(Qt.Horizontal)
        self.horizontalSlider_7 = QSlider(self.speed_pid_box)
        self.horizontalSlider_7.setObjectName(u"horizontalSlider_7")
        self.horizontalSlider_7.setGeometry(QRect(150, 100, 291, 21))
        self.horizontalSlider_7.setOrientation(Qt.Horizontal)
        self.speed_d = QLabel(self.speed_pid_box)
        self.speed_d.setObjectName(u"speed_d")
        self.speed_d.setGeometry(QRect(10, 100, 111, 21))

        self.verticalLayout.addWidget(self.speed_pid_box)

        self.camera_angle_box = QGroupBox(self.centralwidget)
        self.camera_angle_box.setObjectName(u"camera_angle_box")
        self.camera_angle_box.setGeometry(QRect(810, 150, 251, 61))
        self.camera_angle_bar = QSlider(self.camera_angle_box)
        self.camera_angle_bar.setObjectName(u"camera_angle_bar")
        self.camera_angle_bar.setGeometry(QRect(10, 20, 231, 22))
        self.camera_angle_bar.setOrientation(Qt.Horizontal)
        self.camera_capture_recording = QGroupBox(self.centralwidget)
        self.camera_capture_recording.setObjectName(u"camera_capture_recording")
        self.camera_capture_recording.setGeometry(QRect(810, 310, 251, 101))
        self.capture_button = QPushButton(self.camera_capture_recording)
        self.capture_button.setObjectName(u"capture_button")
        self.capture_button.setGeometry(QRect(10, 20, 111, 71))
        self.recording_button = QPushButton(self.camera_capture_recording)
        self.recording_button.setObjectName(u"recording_button")
        self.recording_button.setGeometry(QRect(130, 20, 111, 71))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_mode.setTitle(QCoreApplication.translate("MainWindow", u"Action Mode", None))
        self.action_normal.setText(QCoreApplication.translate("MainWindow", u"Normal", None))
        self.action_voice.setText(QCoreApplication.translate("MainWindow", u"Voice", None))
        self.action_clingy.setText(QCoreApplication.translate("MainWindow", u"Clingy", None))
        self.camera_light_mode.setTitle(QCoreApplication.translate("MainWindow", u"Camera Light Mode", None))
        self.constant_button.setText(QCoreApplication.translate("MainWindow", u"Constant", None))
        self.flash_button.setText(QCoreApplication.translate("MainWindow", u"Flash", None))
        self.image_label.setText(QCoreApplication.translate("MainWindow", u"Image Transmission", None))
        self.realtime_plotting.setTitle(QCoreApplication.translate("MainWindow", u"Realtime Balancing Robot Plotting", None))
        self.moving_speed.setTitle(QCoreApplication.translate("MainWindow", u"Moving Speed", None))
        self.control_panel.setTitle(QCoreApplication.translate("MainWindow", u"Control Panel", None))
        self.left_button.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.right_button.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.backward_button.setText(QCoreApplication.translate("MainWindow", u"Backward", None))
        self.forward_button.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
        self.stop_button.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.start_button.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.pause_button.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.save_button.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.serial_device.setTitle(QCoreApplication.translate("MainWindow", u"Serial Device", None))
        self.detect_button.setText(QCoreApplication.translate("MainWindow", u"Detect", None))
        self.auto_save_check.setText(QCoreApplication.translate("MainWindow", u"Auto Save", None))
        self.connect_button.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.camera_source_box.setTitle(QCoreApplication.translate("MainWindow", u"Camera Source", None))
        self.cam_ip_label.setText(QCoreApplication.translate("MainWindow", u"Cam IP:", None))
        self.ip_modify_button.setText(QCoreApplication.translate("MainWindow", u"Modify", None))
        self.car_ip_label.setText(QCoreApplication.translate("MainWindow", u"Car IP:", None))
        self.battery_level_box.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.battery_label.setText(QCoreApplication.translate("MainWindow", u"Battery Level", None))
        self.angle_pid_box.setTitle(QCoreApplication.translate("MainWindow", u"Angle PID", None))
        self.angle_p.setText(QCoreApplication.translate("MainWindow", u"Propotional Gain", None))
        self.angle_i.setText(QCoreApplication.translate("MainWindow", u"Integral Gain", None))
        self.angle_d.setText(QCoreApplication.translate("MainWindow", u"Derivative Gain", None))
        self.speed_pid_box.setTitle(QCoreApplication.translate("MainWindow", u"Speed PID", None))
        self.speed_p.setText(QCoreApplication.translate("MainWindow", u"Propotional Gain", None))
        self.speed_i.setText(QCoreApplication.translate("MainWindow", u"Integral Gain", None))
        self.speed_d.setText(QCoreApplication.translate("MainWindow", u"Derivative Gain", None))
        self.camera_angle_box.setTitle(QCoreApplication.translate("MainWindow", u"Camera Angle", None))
        self.camera_capture_recording.setTitle(QCoreApplication.translate("MainWindow", u"Camera Capture&Recording", None))
        self.capture_button.setText(QCoreApplication.translate("MainWindow", u"Capture", None))
        self.recording_button.setText(QCoreApplication.translate("MainWindow", u"Recording", None))
    # retranslateUi

